### ISSUE TITLE
GetPriceGuideAsync does not support the 'vat' parameter

### ISSUE THREAD

**Issue by V3oD3o** [gebirgslok/BricklinkSharp#11]
Indicates that price will include VAT for the items of VAT enabled stores. Available values are:
- "N": Exclude VAT (default)
- "Y": Include VAT
- "O": Include VAT as Norway settings

See https://www.bricklink.com/v3/api.page?page=get-price-guide

**Comment by gebirgslok** [comment]
Thanks for reporting. Are you willing to submit a PR? ATM I'm short of time.

BR

**Comment by V3oD3o** [comment]
Sure, I'll give it a try

**Comment by gebirgslok** [comment]
#12
