### ISSUE TITLE
Exception updating inventory items

### ISSUE THREAD

**Issue by stephanstapel** [gebirgslok/BricklinkSharp#13]
Hi,
did you ever come across this return code 400 when updating inventory items:

```console
System.AggregateException: One or more errors occurred. (Received unexpected HTTP status code for request 'PUT'
https://api.bricklink.com/api/store/v1/inventories/331747049:
Expected = 200, received = 400.
Description: A request has been made with a malformed JSON body., message: INVALID_REQUEST_BODY.)
 ---> BricklinkSharp.Client.BricklinkHttpErrorException: Received unexpected HTTP status code for request 'PUT' https://api.bricklink.com
/api/store/v1/inventories/331747049:
Expected = 200, received = 400.
Description: A request has been made with a malformed JSON body., message: INVALID_REQUEST_BODY.
   at BricklinkSharp.Client.Extensions.JsonExtensions.GetData(JsonDocument document, Int32 expectedCode, String url, HttpMethod httpMethod)
   at BricklinkSharp.Client.Extensions.HttpClientExtensions.ParseResponse[TData](String responseBody, Int32 expectedCode, String url, HttpMethod httpMethod)
   at BricklinkSharp.Client.Extensions.HttpClientExtensions.ExecuteReadResponseAsync[TResponse](HttpClient httpClient, HttpMethod method, String url, Int32 expectedCode, Object body, JsonSerializerOptions jsonSerializerOptions, CancellationToken cancellationToken)
   at BricklinkSharp.Client.BricklinkClient.UpdateInventoryAsync(Int32 inventoryId, UpdateInventory updateInventory, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
```

The JSON object looks like this:

```json
{"quantity":"unit_price":0.6000,"description":null,"remarks":"SPC.0015","bulk":null,"is_retain":null,"is_stock_room":false,"stock_room_id":null,"my_cost":null,"sale_rate":null,"tier_quantity1":null,"tier_quantity2":null,"tier_quantity3":null,"tier_price1":null,"tier_price2":null,"tier_price3":null}
```

I found it. quantity is empty!

With the quantity being optional:

![grafik](https://user-images.githubusercontent.com/2912080/226617046-ba3af9d4-0a97-418f-bbab-c6e0dc67acdc.png)

could this be the problem:

![grafik](https://user-images.githubusercontent.com/2912080/226625587-57626284-18a4-45ea-8eb2-273efb62a3f3.png)

**Comment by gebirgslok** [comment]
Oha,
Good Catch @stephanstapel. That check for 0 (value) messes Up the json serialization. Instead, the converter should write "+0". The Check for null ist fine because null properties are ignored when writing anyway 

Are there any other other custom json converters that might be affected by a similiar Bug?

Are willing to submit a PR?

Thanks and BR
Jens

**Comment by gebirgslok** [comment]
The converter has another issue. If the changedQuantity is negative, it should write a minus sign ( e.g. "-5"), according to https://www.bricklink.com/v3/api.page?page=update-inventory

**Comment by stephanstapel** [comment]
> Oha, Good Catch @stephanstapel. That check for 0 (value) messes Up the json serialization. Instead, the converter should write "+0". The Check for null ist fine because null properties are ignored when writing anyway
> 
> Are there any other other custom json converters that might be affected by a similiar Bug?
> 
> Are willing to submit a PR?
> 
> Thanks and BR Jens

the rest looks good. Just a small doubt in NullableItemTypeStringConverter and ItemTypeStringConverter here:

![grafik](https://user-images.githubusercontent.com/2912080/226720901-f59b85f2-20e7-4a0b-b154-b1d87dc245ca.png)

is it correct to return 0 (Minifig) as a default?

**Comment by stephanstapel** [comment]
> The converter has another issue. If the changedQuantity is negative, it should write a minus sign ( e.g. "-5"), according to https://www.bricklink.com/v3/api.page?page=update-inventory

that should come automatically I guess :)

**Comment by gebirgslok** [comment]
Lol, indeed. 😄

**Comment by gebirgslok** [comment]
> > Oha, Good Catch @stephanstapel. That check for 0 (value) messes Up the json serialization. Instead, the converter should write "+0". The Check for null ist fine because null properties are ignored when writing anyway
> > Are there any other other custom json converters that might be affected by a similiar Bug?
> > Are willing to submit a PR?
> > Thanks and BR Jens
> 
> the rest looks good. Just a small doubt in NullableItemTypeStringConverter and ItemTypeStringConverter here:
> 
> ![grafik](https://user-images.githubusercontent.com/2912080/226720901-f59b85f2-20e7-4a0b-b154-b1d87dc245ca.png)
> 
> is it correct to return 0 (Minifig) as a default?

Not really, maybe it's better to throw in Case the parse fails?

**Comment by stephanstapel** [comment]
> > > Oha, Good Catch @stephanstapel. That check for 0 (value) messes Up the json serialization. Instead, the converter should write "+0". The Check for null ist fine because null properties are ignored when writing anyway
> > > Are there any other other custom json converters that might be affected by a similiar Bug?
> > > Are willing to submit a PR?
> > > Thanks and BR Jens
> > 
> > 
> > the rest looks good. Just a small doubt in NullableItemTypeStringConverter and ItemTypeStringConverter here:
> > ![grafik](https://user-images.githubusercontent.com/2912080/226720901-f59b85f2-20e7-4a0b-b154-b1d87dc245ca.png)
> > is it correct to return 0 (Minifig) as a default?
> 
> Not really, maybe it's better to throw in Case the parse fails?

yap, could you do this? I guess you know more about the base idea of your library. In my libraries, I usually add an Unknown value to all enums and leave it for the user to handle this. A bit unfair to be honest :)
