### ISSUE TITLE
Brickowl question

### ISSUE THREAD

**Issue by stephanstapel** [gebirgslok/BricklinkSharp#15]
sorry for this wild post, I just have no idea how to reach you differently.
Did you ever consider creating a BrickOwl adapter for .net? In case of yes, I'm volunteering to assist :)

**Comment by gebirgslok** [comment]
Heyho, 
a BO Client is on my list but unfortunately postponed for unknown time because of Family biz 👶

However, die BO API Integration should be way easier than BL because it uses the simple API key method for auth (this OAuth1 method of BL drove me nuts)

Best

**Comment by stephanstapel** [comment]
alright, thanks. Is it possible that you copy the boilerplate stuff from the other projects and kick off the brickowl adapter? I'm happy to add the main functionality then. I just think that the base stuff would be way easier for you. Just asking.

**Comment by gebirgslok** [comment]
I'll see if I can set somthing up in the next time and let you know :)

**Comment by stephanstapel** [comment]
Just a quick shot:
https://github.com/stephanstapel/BrickOwlSharp
I've just partially implemented wishlists so far, just to test if it works.

If you can spend some time investigating the shameless copies of your code, I'd be more than happy. Also willing for you to take over ownership, I'm not intending to claim anything!

**Comment by gebirgslok** [comment]
Hey,

I think the best approach would bei to Take the rebrickableSharp repo as the Basis because this API uses API key auth as well.

You can Provider me ownership of this repo so i can Setup everything (ci, nuget, etc)

Best
