### ISSUE TITLE
OrderDetails.Shipping.Address does not contain the Phone Number

### ISSUE THREAD

**Issue by IainFr** [gebirgslok/BricklinkSharp#16]
Hello,

Task<OrderDetails> GetOrderAsync(int orderId, CancellationToken cancellationToken = default(CancellationToken));
the returned OrderDetails.Shipping.Address  does not contain the Phone Number as detailed in the Bricklink docs here:

https://www.bricklink.com/v3/api.page?page=resource-representations-order
[shipping.address.phone_number] | String | The buyer's phone number

Thank you
Iain

**Comment by gebirgslok** [comment]
Hey lain,
Thanks for reporting. I'll add it in the next days.

Best

**Comment by IainFr** [comment]
Thank you kindly, I will look out for it... Iain

**Comment by gebirgslok** [comment]
I just added the phone no to the response object and published a new version to nuget.

PS: don't 4get to leave a star for this repo :)
