### ISSUE TITLE
GetPartOutValueFromPageAsync for >$1k sets returns just thousands as single digit

### ISSUE THREAD

**Issue by norberto5** [gebirgslok/BricklinkSharp#22]
Well, maybe an example will show what I mean:
![image](https://github.com/gebirgslok/BricklinkSharp/assets/4960972/9fcd00f1-ae79-41b7-9c59-2f127cf6e89d)

If the part out value is above $1,000.00 then the code cuts hundreds, and it's returned as $1

Example sets with the issue:
10307
75313

**Comment by gebirgslok** [comment]
Thanks for contributing, new version 1.6.2 released (I also added some unit tests ;D)

**Comment by gebirgslok** [comment]
#23
