### ISSUE TITLE
Retrieve thumbnail image url

### ISSUE THREAD

**Issue by stephanstapel** [gebirgslok/BricklinkSharp#25]
Hi,

I find this function pretty useful:

https://github.com/gebirgslok/BricklinkSharp/blob/be8654186142a73bc7b46328ea36d0258a64b1c8/BricklinkSharp.Client/BricklinkClient.cs#L155

and found on the other hand, that the API seems to be returning thumbnail urls for other colors (I might be wrong though).
Would you mind if I add a function for retrieving the thumbnail url just like the image url?

Cheers,

Stephan

**Comment by gebirgslok** [comment]
Released 1.7.0
